import { useEffect, useState } from "react";
import { Activity, Bot, ChevronRight, RotateCcw, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { listAgentLogs, runRecoveryAgent, subscribeToAgentLogs } from "@/services/agentService";
import { useRecoveryCases } from "@/services/dashboardService";

export default function AgentLive() {
  const [logs, setLogs] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [running, setRunning] = useState(false);
  const recoveryQuery = useRecoveryCases(true); const serverActivity = trpc.agent.activity.useQuery(undefined, { retry: false, staleTime: 15_000 });
  const refresh = async () => { setLoading(true); try { setLogs(await listAgentLogs()); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); return subscribeToAgentLogs(() => { void refresh(); void serverActivity.refetch(); toast.success("Agent activity updated"); }); }, []);
  const displayLogs = logs.length ? logs : (serverActivity.data ?? []).map((log: any) => ({ id: log.id, recovery_case_id: log.recoveryCaseId, event_type: log.eventType, message: log.message, metadata: log.metadata, created_at: log.createdAt }));
  const run = async () => { const paymentId = recoveryQuery.data?.find((item: any) => item.paymentId)?.paymentId; if (!paymentId) return toast.error("No recovery payment is available"); setRunning(true); try { const result = await runRecoveryAgent(paymentId); toast.success(`Agent decision: ${result.decision.recommended_action}`); await refresh(); await serverActivity.refetch(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to run recovery agent"); } finally { setRunning(false); } };
  return <><div className="page-header"><div><div className="eyebrow text-cobalt">AI / Operations</div><h1 className="page-title">Recovery agent</h1><p className="page-subtitle">A policy-aware agent that inspects payment context, predicts recovery, and executes only bounded actions.</p></div><button className="button-primary" onClick={run} disabled={running}><Sparkles size={15}/>{running ? "Agent running..." : "Run agent"}</button></div><div className="grid gap-4 md:grid-cols-3"><section className="surface p-5"><Bot className="text-cobalt" size={18}/><div className="mt-5 text-xs text-muted">Current mode</div><div className="mt-1 text-lg font-semibold text-ink">Policy constrained</div></section><section className="surface p-5"><Activity className="text-mint-strong" size={18}/><div className="mt-5 text-xs text-muted">Observed steps</div><div className="mt-1 text-lg font-semibold text-ink">{displayLogs.length || "—"}</div></section><section className="surface p-5"><div className="eyebrow text-cobalt">Guardrail</div><div className="mt-5 text-sm font-semibold text-ink">No captured-payment actions</div><div className="mt-1 text-xs text-muted">All decisions are checked against merchant policy.</div></section></div><section className="surface mt-5 overflow-hidden"><div className="flex items-center justify-between border-b border-line p-5"><div><div className="eyebrow">Live agent activity</div><h2 className="mt-2 text-lg font-semibold text-ink">Tool calls and decisions</h2></div><button className="filter-button" onClick={refresh}><RotateCcw size={14}/> Refresh</button></div>{loading || serverActivity.isLoading ? <div className="p-6 text-sm text-muted">Loading agent activity…</div> : <div className="overflow-x-auto"><table className="ledger"><thead><tr><th>Time</th><th>Case</th><th>Tool</th><th>Decision</th><th>Policy result</th><th /></tr></thead><tbody>{displayLogs.map((log, index) => <tr key={log.id ?? `${log.recovery_case_id}-${index}`}><td className="font-mono text-[11px] text-muted">{new Date(log.created_at ?? Date.now()).toLocaleTimeString()}</td><td className="font-mono text-xs text-cobalt">{log.recovery_case_id ?? "—"}</td><td className="font-mono text-[11px] text-muted">{log.metadata?.tool_name ?? log.event_type}</td><td className="font-semibold text-ink">{log.message}</td><td>{log.metadata?.policy_result ?? "recorded"}</td><td><ChevronRight size={14} className="text-muted"/></td></tr>)}</tbody></table></div>}</section></>;
}
