import { useEffect, useState } from "react";
import { Code2, FileJson, Filter, Info, RotateCcw, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { listAuditLogs, subscribeToAgentLogs } from "@/services/agentService";

export default function AuditLive() {
  const [logs, setLogs] = useState<any[]>([]); const [loading, setLoading] = useState(true); const serverAudit = trpc.audit.events.useQuery(undefined, { retry: false, staleTime: 15_000 });
  const refresh = async () => { setLoading(true); try { setLogs(await listAuditLogs()); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); return subscribeToAgentLogs(() => { void refresh(); void serverAudit.refetch(); }); }, []);
  const displayLogs = logs.length ? logs : (serverAudit.data ?? []).map((log: any) => ({ id: log.id, recovery_case_id: log.caseId, event_type: log.actionType, message: log.toolName, metadata: { policy_result: log.status, tool_name: log.toolName }, created_at: log.executedAt }));
  return <><div className="page-header"><div><div className="eyebrow text-cobalt">AI / Governance</div><h1 className="page-title">AI decision audit trail</h1><p className="page-subtitle">A transparent record of every prediction, policy check, and bounded recovery action.</p></div><button className="button-secondary" onClick={() => toast.success("Audit log export queued")}><FileJson size={14}/> Export JSON</button></div><div className="mb-5 flex flex-wrap gap-2"><button className="filter-button"><RotateCcw size={14}/> Live updates</button><button className="filter-button"><Filter size={14}/> All cases</button><button className="filter-button"><Code2 size={14}/> All tools</button><button className="filter-button"><ShieldCheck size={14}/> Policy checked</button></div><section className="surface overflow-hidden"><div className="overflow-x-auto">{loading || serverAudit.isLoading ? <div className="p-6 text-sm text-muted">Loading audit history…</div> : <table className="ledger"><thead><tr><th>Timestamp</th><th>Case</th><th>Event</th><th>Tool</th><th>Decision</th><th>Policy result</th><th>Status</th></tr></thead><tbody>{displayLogs.map((log, index) => <tr key={log.id ?? `${log.recovery_case_id}-${index}`}><td className="font-mono text-[11px] text-muted">{new Date(log.created_at ?? Date.now()).toLocaleString()}</td><td className="font-mono text-xs text-cobalt">{log.recovery_case_id ?? "—"}</td><td className="font-semibold text-ink">{log.event_type}</td><td className="font-mono text-[11px] text-muted">{log.metadata?.tool_name ?? "system"}</td><td>{log.message}</td><td>{log.metadata?.policy_result ?? "recorded"}</td><td><span className="pill pill-mint">Recorded</span></td></tr>)}</tbody></table>}</div></section><div className="mt-5 flex items-center gap-2 text-xs text-muted"><Info size={14}/> Every row stores tool inputs, outputs, policy result, and timestamp metadata.</div></>;
}
